services:
  web:
    image: nginx:1.29-alpine
    container_name: ff-web-server
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped