services:
  web:
    image: nginx:1.29-alpine
    container_name: ff-web-server
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./style.css:/usr/share/nginx/html/style.css
      - ./script.js:/usr/share/nginx/html/script.js
      - ./coi-serviceworker.min.js:/usr/share/nginx/html/coi-serviceworker.min.js
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped